# Generated by Django 4.2.7 on 2023-11-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
